name: Release chart
on:
  push:
    tags:
      - "charts/[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      CHART_DIR: charts/jwt-to-rbac
      CHART_REGISTRY: oci://ghcr.io/${{ github.repository_owner }}/charts
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Helm
        uses: azure/setup-helm@v5

      - name: Check chart version
        run: |
          CHART_VERSION=$(yq '.version' "${CHART_DIR}/Chart.yaml")
          if [[ "${GITHUB_REF_NAME#charts/}" != "${CHART_VERSION}" ]]; then
            echo "::error::Tag ${GITHUB_REF_NAME} does not match chart version ${CHART_VERSION}"
            exit 1
          fi

      - name: Login to GitHub Container Registry
        run: echo "${GITHUB_TOKEN}" | helm registry login ghcr.io --username "${GITHUB_ACTOR}" --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package chart
        run: helm package "${CHART_DIR}" --destination .helm-release

      - name: Push chart
        run: helm push .helm-release/*.tgz "${CHART_REGISTRY}"
