name: CI
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "charts/**"
      - "docs/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v1

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-check

      - name: Build code
        run: make build

  acceptance-test:
    name: Acceptance test
    runs-on: ubuntu-latest
    env:
      DOCKER_LATEST: 1
      VERSION: latest

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          make docker

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: "acceptance-test"

      - name: Load Docker images to kind
        run: |
          kind load docker-image --name acceptance-test banzaicloud/jwt-to-rbac:latest

      - name: Run make check
        run: |
          make check
