name: CI
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Check out code
      uses: actions/checkout@v1

    - name: Check licenses
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make license-check

    - name: Buld code
      run: make build

  acceptance-test:
    name: Acceptance test
    runs-on: ubuntu-latest
    env:
      KURUN_VERSION: "0.4.1"
      DOCKER_LATEST: 1
      VERSION: latest

    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        make docker

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.0.0

    - name: Load Docker images to kind
      run: |
        kind load docker-image banzaicloud/jwt-to-rbac:latest

    - name: Run make check
      run: |
        make check
